<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>ClinicManager.Application.UnitTests</RootNamespace>
        <AssemblyName>ClinicManager.Application.UnitTests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Identity" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="nunit" />
        <PackageReference Include="NUnit.Analyzers">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NUnit3TestAdapter" />
        <PackageReference Include="Moq" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Server\Application\Application.csproj" />
        <ProjectReference Include="..\..\Server\Infrastructure\Infrastructure.csproj" />
    </ItemGroup>

</Project>
